<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  bookstore [
	<!ELEMENT bookstore (book+) >
	<!ELEMENT book (title, author, isbn, publisher, edition,price)>	
	<!ELEMENT title (#PCDATA) >
	<!ELEMENT author (#PCDATA)>
 <!ELEMENT isbn (#PCDATA)>
 <!ELEMENT publisher (#PCDATA)>
 <!ELEMENT edition (#PCDATA)>
 <!ELEMENT price (#PCDATA)>
]>



<bookstore>
 	<book>
		<title>XML Basics</title>
		<author>John Doe</author>
		<isbn>123-456-789</isbn>
		<publisher>ABC Publications</publisher>
		<edition>1st</edition>
		<price>29.99</price>
	</book>
</bookstore>